export type LoungeSettings = {
	turn_timer_seconds: number;
	max_players: number;
	small_blind: number;
	big_blind: number;
	default_buy_in: number;
};

export const DEFAULT_LOUNGE_SETTINGS: LoungeSettings = {
	turn_timer_seconds: 30,
	max_players: 9,
	small_blind: 5,
	big_blind: 10,
	default_buy_in: 1000
};

export type Profile = {
	id: string;
	display_name: string;
	bio: string | null;
	avatar_url: string | null;
	created_at: string;
	updated_at: string;
};

export type Lounge = {
	id: string;
	code: string;
	name: string;
	owner_id: string;
	persistent: boolean;
	created_at: string;
	last_active_at: string;
	settings: LoungeSettings;
};

export type LoungeRole = 'owner' | 'member';

export type LoungeMember = {
	lounge_id: string;
	user_id: string;
	role: LoungeRole;
	joined_at: string;
};

export type LoungeMemberWithProfile = LoungeMember & {
	profile: Pick<Profile, 'display_name' | 'avatar_url'>;
};

// Note: the canonical Supabase Database type is generated by `supabase gen
// types typescript`. We don't run that here yet, so the helpers in
// `$lib/db/*` cast results to the row types defined above at the boundary.
// Once the project stabilizes, replace this with the generated type.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
